FROM microsoft/aspnetcore-build AS builder
WORKDIR /app

COPY . ./

RUN dotnet restore

ENV ASPNETCORE_ENVIRONMENT Production

RUN cd services/ShopOnline/Bountique.Api/ && dotnet publish -c Release -o bin/Docker/

WORKDIR /app/services/ShopOnline/Bountique.Api/bin/Docker

ENV ASPNETCORE_URLS "http://*:5000"

ENTRYPOINT ["dotnet", "Bountique.Api.dll"]